/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'swaroop.veeram' at '10/9/17 2:58 PM' with Gradle 1.11
 *
 * @author swaroop.veeram, @date 10/9/17 2:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
